# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseOne',
        ),
        migrations.DeleteModel(
            name='CourseTwo',
        ),
    ]
