# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161230_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseonevideoques',
            options={'verbose_name': 'Course One Video Question', 'verbose_name_plural': 'Course One Video Questions'},
        ),
    ]
