# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161230_0706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetwovideo',
            options={'verbose_name': 'Course Two Video', 'verbose_name_plural': 'Course Two Videos'},
        ),
    ]
