# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161230_0845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetwoques',
            options={'verbose_name': 'Course Two Question', 'verbose_name_plural': 'Course Two Questions'},
        ),
    ]
