# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161230_0846'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseonevideoques',
            unique_together=set([('video', 'ques_no')]),
        ),
    ]
