# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161230_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(default='asdfasdfadfasdf', max_length=20),
        ),
    ]
