# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170102_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emp_id',
            field=models.CharField(default='asdfasdfadfasdf', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emp_name',
            field=models.CharField(default='nahi pata', max_length=30),
        ),
    ]
